<?php


namespace App\Tests\Service;


use PHPUnit\Framework\TestCase;

class OvertimeServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}